# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: willibrandon.pgtail
PackageVersion: 0.1.0
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: portable
Commands:
  - pgtail
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/willibrandon/pgtail/releases/download/v0.1.0/pgtail-windows-x86_64.exe
    InstallerSha256: PLACEHOLDER_SHA256_WINDOWS
ManifestType: installer
ManifestVersion: 1.6.0
